# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ram3i-OPR6_Y2jlAgiuz-EnMLA55dnR
"""

from pathlib import Path
import pandas as pd

COLS = [
    "id1","cell","step","id2","count","date","clock",
    "t_min","V_mV","I_mA","Q_mAh","E_mWh","P_W"
]

def load_by_prefix(prefix, folder="."):
    files = sorted(Path(folder).glob(f"{prefix}*.txt"))
    dfs = []
    for f in files:
        df = pd.read_csv(f, header=None, delim_whitespace=True)
        df.columns = COLS
        df["source"] = f.name
        dfs.append(df)
    return pd.concat(dfs, ignore_index=True)